spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/toy
    username: sa
    password: '0000'
    driver-class-name: org.h2.Driver

  devtools:
    restart:
      enabled: true
    thymeleaf:
      cache: false
      prefix: file:src/main/resources/templates/

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

logging:
  level: debug
#  org.hibernate.type: trace